#pragma once
enum class TextureLoadType 
{
	TILE_PLAIN,
	TILE_BUSH_BERRY,
	TILE_BUSH_FIBER,
	TILE_ROCK,
	TILE_ROCK_DEMOLISHED,
	TILE_TREE,
	TILE_TREE_STUMP,

	ENTITY_HUMAN,
	ENTITY_HUMAN_CROUCH,
	ENTITY_HUMAN_WITH_SPEAR,
	ENTITY_HUMAN_WITH_SPEAR_CROUCH,

	ENTITY_RABBIT,
	ENTITY_DEER,
	ENTITY_ELK,
	ENTITY_GOOSE,
	ENTITY_WOLF,
	ENTITY_BEAR
};